# Generated by Django 5.0.6 on 2024-07-16 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passapp', '0002_alter_myuser_phone_alter_perevaladded_author_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perevaladded',
            old_name='coord_id',
            new_name='coords',
        ),
        migrations.RenameField(
            model_name='perevaladded',
            old_name='author_id',
            new_name='user',
        ),
    ]
