# Generated by Django 5.0.6 on 2024-07-16 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='phone',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='perevaladded',
            name='author_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='passapp.myuser'),
        ),
        migrations.AlterField(
            model_name='perevaladded',
            name='connect',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
