# Generated by Django 5.0.6 on 2024-07-16 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passapp', '0003_rename_coord_id_perevaladded_coords_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perevaladded',
            name='status',
            field=models.CharField(choices=[('NW', 'New'), ('PN', 'Pending'), ('AC', 'Accepted'), ('RJ', 'Rejected')], default='NW', max_length=10),
        ),
    ]
